# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := framework WorldScene

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

framework: 
	@echo "==== Building framework ($(config)) ===="
	@${MAKE} --no-print-directory -C ../tutoriale/Tutorial\ 0.3.8/framework -f Makefile

WorldScene: framework
	@echo "==== WorldScene ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f WorldScene.make

clean:
	@${MAKE} --no-print-directory -C ../tutoriale/Tutorial\ 0.3.8/framework -f Makefile clean
	@${MAKE} --no-print-directory -C . -f WorldScene.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   framework"
	@echo "   WorldScene"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
